name: Ruby

on: push

jobs:
  main:
    name: Run spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.5"
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec
